import './lib/lang-switcher.js';
import './lib/slider.js';
import './lib/hover-slider.js';
import './lib/search.js';
import './lib/drop-scroll.js';
import './lib/popap.js';
import './lib/popap-slider.js';
import './lib/video.js';
import './lib/video-play-stop.js';
import './lib/switcher.js';

import './lib/menu-mobile.js';
import './lib/select2.js';
import './lib/drop.js';
import './lib/slider-direction.js';
import './lib/breadcrombs.js';
import './lib/slider-vnedrenie.js';
import './lib/popap-napravlenie';
import './lib/dot.js';
